name: Deploy Laravel Project to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Laravel Project
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: SSH into EC2 and execute php.sh
      - name: Run Deployment Script on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}        # EC2 Host (set in GitHub Secrets)
          username: ubuntu                     # Default EC2 username
          key: ${{ secrets.EC2_PRIVATE_KEY }}  # Private Key for SSH
          port: 22
          script: |
            chmod +x /home/ubuntu/php.sh       # Make the script executable
            /home/ubuntu/php.sh                # Execute the script
